# Data Cleaning
I cleaned and standardized a 440K+ customer dataset by handling nulls, fixing data types, normalizing categorical values, and validating schema before loading it into SQL and Power BI.

- Dataset cleaned and validated using Python (pandas)
- Null values removed
- Data types standardized for SQL and Power BI usage
- Churn is binary (0 = Active, 1 = Churned)

In [1]:
import pandas as pd

# Load raw data
df = pd.read_csv(r"D:\Customer_churn_analysis\Customer-Churn-Analysis-main\1_data\raw\customer_churn_dataset.csv")
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [2]:
# Rename columns
df.columns = [
    'customer_id', 'age', 'gender', 'tenure', 'usage_frequency',
    'support_calls', 'payment_delay', 'subscription_type',
    'contract_length', 'total_spend', 'last_interaction', 'churn'
]
df.head()

,customer_id,age,gender,tenure,usage_frequency,support_calls,payment_delay,subscription_type,contract_length,total_spend,last_interaction,churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [3]:
# Getting Information of total Column & Rows
df.shape

(440833, 12)

In [4]:
# Know Your Coloumns
df.columns

Index(['customer_id', 'age', 'gender', 'tenure', 'usage_frequency',
       'support_calls', 'payment_delay', 'subscription_type',
       'contract_length', 'total_spend', 'last_interaction', 'churn'],
      dtype='object')

In [5]:
# Dataset Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   customer_id        440832 non-null  float64
 1   age                440832 non-null  float64
 2   gender             440832 non-null  object
 3   tenure             440832 non-null  float64
 4   usage_frequency    440832 non-null  float64
 5   support_calls      440832 non-null  float64
 6   payment_delay      440832 non-null  float64
 7   subscription_type  440832 non-null  object
 8   contract_length    440832 non-null  object
 9   total_spend        440832 non-null  float64
 10  last_interaction   440832 non-null  float64
 11  churn              440832 non-null  float64
dtypes: float64(9), object(3)
memory usage: 40.4+ MB

In [6]:
# Dataset Duplicate Value Count
duplicate_values = df.duplicated().value_counts()  
duplicate_values

False    440833
Name: count, dtype: int64

In [7]:
# Missing Values/Null Values Count
df.isnull().sum()

customer_id          1
age                  1
gender               1
tenure               1
usage_frequency      1
support_calls        1
payment_delay        1
subscription_type    1
contract_length      1
total_spend          1
last_interaction     1
churn                1
dtype: int64

In [8]:
# Drop Null Values
df = df.dropna()

In [9]:
# Remove nulls safely
df = df.dropna().copy()

# Convert data types
int_cols = [
    'customer_id', 'age', 'tenure', 'usage_frequency',
    'support_calls', 'payment_delay', 'last_interaction', 'churn'
]

df[int_cols] = df[int_cols].astype(int)
df['total_spend'] = df['total_spend'].astype(float)

In [10]:
# Standardize text columns
text_cols = ['gender', 'subscription_type', 'contract_length']

for col in text_cols:
    df[col] = df[col].str.strip().str.title()

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 440832 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   customer_id        440832 non-null  int64
 1   age                440832 non-null  int64
 2   gender             440832 non-null  object
 3   tenure             440832 non-null  int64
 4   usage_frequency    440832 non-null  int64
 5   support_calls      440832 non-null  int64
 6   payment_delay      440832 non-null  int64
 7   subscription_type  440832 non-null  object
 8   contract_length    440832 non-null  object
 9   total_spend        440832 non-null  float64
 10  last_interaction   440832 non-null  int64
 11  churn              440832 non-null  int64
dtypes: float64(1), int64(8), object(3)
memory usage: 43.7+ MB

In [12]:
# Save cleaned data
df.to_csv(
    r"D:\Customer_churn_analysis\Customer-Churn-Analysis-main\1_data\processed\customer_churn_cleaned.csv",
    index=False
)

print("✅ Data cleaning completed")

✅ Data cleaning completed